theme: jekyll-theme-minimal

title: Emma Waugh's Portfolio
description: My name is Emma, and I'm a senior studying geology, food systems, and environmental studies at Middlebury College. This page serves as a portfolio of all the work⁠ I've done in [GEOG 323: Open Source GIScience](gis4dev.github.io).
avatar: emwaugh.github.io/assets/emma.jpeg
